### ISSUE TITLE
Python not working with Flatpak install

### ISSUE THREAD

**Issue by aplatypus** [flathub/org.processing.processingide#5]
Hi -- I just wanted to try Processing with Python so I used the Flatpak version.  However it does not look like the flatpak and work with Python.

See the messages from the console.  it keeps saying that it "`assumes a registry is created on port 8220`".  Nothing actually happens so I do not believe this resgistry has been created.

```
 $ flatpak run org.processing.processingide
 $ You are running Processing revision 0265, the latest build is 0269.
 $ 
 $ created registry at port 8220
could not create registry; assume it's already created
Reference Tool 1.1.1 by Jae Hyun
could not create registry; assume it's already created
```

Is there something I need to do to activate with Python to and the Flatpak installer?

This is 64-bit ubuntu 19.04
All packages are up to date.

**Comment by hfiguiere** [comment]
do you have a step by step to reproduce?

**Comment by zWhdmB5T** [comment]
@aplatypus @hfiguiere Well, I use the current v4.2 and I can use Python within the Processing IDE. Not sure what about @aplatypus … (I just tried it explicitly — usually I use Java mode of Processing.)

**Comment by Zishan-Rahman** [comment]
@zWhdmB5T (sorry for the ping) I updated this Flatpak from version 4.2 to 4.3 last week (it went live on the 22<sup>nd</sup> after some initial build server issues), and have made some other changes to it since then. I usually just stick with Java mode when trying out Processing, but seeing as this issue was open for so long, I decided to install Python mode and try out some Processing sketches written in Python. While I can _open_ these sketches, I actually did run into some issues of my own when trying to _run_ them in the Processing IDE. I'm also having the same issues with just running the extracted binaries _outside_ of this Flatpak, but since you said things were working on _your_ end before the update, I'd kindly like to ask you the following: Since this Flatpak has been updated to version 4.3, have _you_ run into any issues while trying the Python mode (as of now)? Has anything changed on your end or do things still work?

For reference, here are the errors _I'm_ getting when trying Python mode (Java mode runs just fine). The first time I try to run the Threads example:

```
java.lang.UnsatisfiedLinkError: Can't load library: /app/share/processing/natives/linux-amd64/libgluegen_rt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:492)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:146)
	at processing.core.PApplet.initSurface(PApplet.java:10215)
	at jycessing.PAppletJythonDriver.initSurface(PAppletJythonDriver.java:472)
	at processing.core.PApplet.runSketch(PApplet.java:10121)
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:909)
	at jycessing.Runner.runSketchBlocking(Runner.java:409)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

And the second time:

```
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.newt.NewtFactory
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:492)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:146)
	at processing.core.PApplet.initSurface(PApplet.java:10215)
	at jycessing.PAppletJythonDriver.initSurface(PAppletJythonDriver.java:472)
	at processing.core.PApplet.runSketch(PApplet.java:10121)
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:909)
	at jycessing.Runner.runSketchBlocking(Runner.java:409)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can't load library: /app/share/processing/natives/linux-amd64/libgluegen_rt.so [in thread "processing.py mode runner"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
	... 9 more
```

And opening the Flatpak in Python mode to start with:

```
~$ flatpak run org.processing.processingide 
created registry at port 8220
/home/madeupusername/sketchbook/modes/PythonMode/formatter/pep8.py:100: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "/home/madeupusername/sketchbook/modes/PythonMode/formatter/format_server.py", line 6, in <module>
    import autopep8
  File "/home/madeupusername/sketchbook/modes/PythonMode/formatter/autopep8.py", line 61, in <module>
    import pep8
  File "/home/madeupusername/sketchbook/modes/PythonMode/formatter/pep8.py", line 1213, in <module>
    init_checks_registry()
  File "/home/madeupusername/sketchbook/modes/PythonMode/formatter/pep8.py", line 1212, in init_checks_registry
    register_check(function)
  File "/home/madeupusername/sketchbook/modes/PythonMode/formatter/pep8.py", line 1195, in register_check
    args = inspect.getargspec(check)[0]
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
WARNING: package com.apple.eawt not in java.desktop
WARNING: package com.apple.eawt not in java.desktop
could not create registry; assume it's already created
```

And loading Python mode from Java mode while the IDE is already open:

```
WARNING: package com.apple.eawt not in java.desktop
WARNING: package com.apple.eawt not in java.desktop
could not create registry; assume it's already created
```

**Comment by zWhdmB5T** [comment]
Dear @Zishan-Rahman  I'm not sure what specific example you are talking about, sorry.

I have used just Java mode within Processing IDE in the past. But when reading that origin post, I wanted to see and try out. My current system, currently:

* Processing IDE 4.3 Flatpak
* on openSUSE Leap 15.5
* Python mode for Processing IDE 4001

I have just tried some simple examples, mostly from ChatGPT. ChatGPT graphic examples mostly didn't run with me. But I have tried the Python example "Topics — Fractals and L-Systems — Mandelbrot" successfully.
![Bildschirmfoto_2023-09-28_10-32-54](https://github.com/flathub/org.processing.processingide/assets/143814533/bea4e7d2-df17-46b4-9949-6aa75ec6d293)

**Comment by Zishan-Rahman** [comment]
> Dear @Zishan-Rahman I'm not sure what specific example you are talking about, sorry.

@zWhdmB5T No worries, I should've been more specific. The example I tried was "Demos — Graphics — Particles" in Python mode. _That_ still fails for me, but weirdly enough, the Mandelbrot example you mentioned works for me in Python mode with the Flatpak on my computer (and it's the same case with the extracted binaries _outside_ of this Flatpak too; I usually test it this way too to ensure it isn't _strictly_ an issue with Flatpak's sandbox). It _could_, at least partially, be down to the ways both are written, as the Mandelbrot sketch is a simple procedural Python script (`Mandelbrot.pyde`) whereas the Particles sketch uses multiple files, functions and classes, with `setup()` and `draw()` functions in the main file (`Particles.pyde`) that I _assume_ are meant to be called when clicking "Run" in the IDE? Not that I'd know for sure. I'm only testing it out just like you are, so my interpretation of things could be quite wrong.

Please can you try the "Demos — Graphics — Particles" Python example with the Flatpak on your computer and see if it works? I'd like to see if we're both on the same page here, then we can try figuring out what to do next.

I'm using Linux Mint 21.2 (based on Ubuntu 22.04 LTS), by the way. The Flatpak (4.3) and Python mode (4001) are both up to date on my end.

**Comment by zWhdmB5T** [comment]
@Zishan-Rahman  Thank you!

OK, we both have

* Processing IDE 4.3 Flatpak installation
* Python Mode for Processing IDE 4001

but on different OS (I have already heard about Linux Mint…) Yours is DEB based, mine is RPM based. Unfortunately, the Processing IDE provided by official repositories on my openSUSE Leap is outdated by far. That is why I use the Flatpak. But be aware, I use it just a little bit and mainly in Java mode only.

I tried your example. At my system, there is no output at all. Nothing in the console window area, nor does a graphical window open. Nothing. But even no error messages. Just nothing.

My Mandelbrot example as stated before works just fine. I recently tried another example, i.e. "Topics — Fractals and L-Systems — Koch". That does consist of three files in total, i.e. more than one single file. And it works. It opens a graphical window and shows the Koch curve animated.

My guess: these Python examples are not necessarily related to Processing IDE Python Mode, but Python examples in general. When I go through all the different Python examples listed there, I would guess they not all of them can run on Processing IDE due to the limited capabilities of Processing IDE. To compare: the Processing IDE Java Mode is some special Java Mode, it's not the regular Java with all capabilities of Java JDK. For Procssing IDE, it is made easier to get running code working and working graphics. It's some way easier than using regular Java. Much less "overhead" of code needed.

**Comment by Zishan-Rahman** [comment]
> My guess: these Python examples are not necessarily related to Processing IDE Python Mode, but Python examples in general. When I go through all the different Python examples listed there, I would guess they not all of them can run on Processing IDE due to the limited capabilities of Processing IDE. To compare: the Processing IDE Java Mode is some special Java Mode, it's not the regular Java with all capabilities of Java JDK. For Procssing IDE, it is made easier to get running code working and working graphics. It's some way easier than using regular Java. Much less "overhead" of code needed.

@zWhdmB5T Sorry for taking so long to write this whole comment (and sorry for the ping, after so long). I get the point you're making, and I tried running the Koch example on my computer and it works just fine. However, I don't think the issues we're having stem from limits in the Processing IDE's capabilities.

In fact, I did some further testing and found out that the problems I have with running Python sketches are specifically coming from those that use the optional `renderer` parameter in the `save(w, h, renderer)` method. [The processing.py documentation](https://py.processing.org/reference/size.html) explains what that parameter is used for, but in a nutshell, it's basically used in the `size` function to tell processing.py which renderer to use for a particular sketch in the `setup()` method of a `.pyde` file (the main file for a Python Processing sketch). The Koch and Mandelbrot sketches do not use this parameter when calling `size`, hence they use the default renderer, and that works fine. Where the issue arises, at least from _my_ observation, is when that optional parameter is used. The Particles sketch uses `P2D` for `renderer` when calling `size`, whereas the BoxClock example (found in "Demos — Graphics — BoxClock") uses `P3D`. On my computer, neither of them run. I tried running Processing 4.3 with Python mode outside of Flatpak's sandbox and the exact same problems occur.

So after looking into it, I _can_ conclude that the problem we're both facing is likely on Python mode's end, and it's not a Flatpak-specific problem. At some point I plan to open an issue in [the processing.py repository](https://github.com/jdf/processing.py/tree/processing4) describing our ordeal. When I've done so, I'll ping you here again so you can subscribe to it and chime in with comments of your own (in case you don't find the issue before then; I haven't opened it yet).

I won't close _this_ issue just yet, as I want to be absolutely certain that the right thing is being done, and also so that anyone else struggling to run some Python sketches with the Flatpak may come across this and hopefully gain some insight as to why these problems may be occurring. I also want to wait until a new version of the Python mode extension comes out that includes a fix to our issue can be downloaded directly through Processing. Hopefully that happens as soon as possible.

Oh, and, just for the sake of reference (and maybe some fun too), here's what the Particles example is _supposed_ to look like (running in Java mode):

![Screenshot from 2023-09-28 14-17-16](https://github.com/flathub/org.processing.processingide/assets/45298929/8ae8e50c-aa7d-46a3-8a88-14e5d7451e2b)

Sidenote:

> Yours is DEB based, mine is RPM based. Unfortunately, the Processing IDE provided by official repositories on my openSUSE Leap is outdated by far. That is why I use the Flatpak. 

You'll most likely know this already, but outdated packages are definitely a thing in DEB-based distros as well, especially since both Debian and Ubuntu LTS are oriented towards having more stable packages than getting all of the latest updates, unlike Arch or openSUSE Tumbleweed. Since Mint uses Ubuntu's repositories for most of its apps and packages, I also use Flatpaks for some apps that are more up-to-date there than in the repositories, and some apps that aren't even _in_ those repositories, as is sometimes the case. The extracted binaries I use to test the Processing IDE outside of Flatpak's sandbox, while trying to resolve this issue, [are in the `.tgz` file(s) provided by the Processing Foundation themselves](https://github.com/processing/processing4/releases/download/processing-1293-4.3/processing-4.3-linux-x64.tgz).

**Comment by Zishan-Rahman** [comment]
@zWhdmB5T I just opened the issue on processing.py's GitHub. I already pinged you in that issue a couple of times, but I just thought I'd let you know about it here as well: jdf/processing.py#420

Feel free to post a comment of your own there as well. I'll keep this issue open for reasons I already stated in my previous comment here. Oh, and sorry for all the pings.

**Comment by zWhdmB5T** [comment]
@Zishan-Rahman Thank you for keeping me informed. I would rather say that I don't have anything special to contribute at the moment, sorry. Thank you for doing the effort.

**Comment by Zishan-Rahman** [comment]
> @Zishan-Rahman Thank you for keeping me informed. I would rather say that I don't have anything special to contribute at the moment, sorry. Thank you for doing the effort.

No worries and you're welcome! At least _now_ we know what the problem is. Hopefully the issue I just opened gets noticed and resolved as soon as possible.

**Comment by aplatypus** [comment]
This is looking promising, thanks everyone.

**Comment by Zishan-Rahman** [comment]
@aplatypus @zWhdmB5T I apologise for the sudden absence of updates on my end.

In the days since I last discussed our Python mode issues here, I noticed that the error generated when initially trying to run a Python sketch using a non-default renderer was trying to locate a library in a folder that didn't exist inside [the `.tgz` file used for this Flatpak](https://github.com/processing/processing4/releases/download/processing-1293-4.3/processing-4.3-linux-x64.tgz): `java.lang.UnsatisfiedLinkError: Can't load library: /app/share/processing/natives/linux-amd64/libgluegen_rt.so`

I decided to try copying the necessary files (they're in the aforementioned `.tgz` file in `core/library`) into the newly created `natives` folder, and I can _run_ Python sketches now. However, I still have trouble _stopping_ them running without having to either close the IDE outright or open my system monitor application (Linux Mint Cinnamon comes with its own System Monitor) and halting that specific process (that way, the IDE itself can stay open). This is the error I get every time I try to stop the running of a Python sketch (either by trying to close the window itself or by clicking the stop button in the IDE itself):

```
Exception in thread "processing.py mode runner" java.lang.NoClassDefFoundError: processing/javafx/PSurfaceFX
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:952)
	at jycessing.Runner.runSketchBlocking(Runner.java:409)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: processing.javafx.PSurfaceFX
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 4 more
```

The solution to _this_ problem is less obvious to me right now, as I can't find a `PSurfaceFX` file in the `.tgz` file. I also tried building Processing from source, where a `PSurfaceFX.java` source file _does_ exist, but the problem still persists. Nonetheless, I'm sure this will be worth looking into at some point. 

Even though it's not a complete fix, and, in my opinion, it's a rather hacky fix, it's still a start, and I think it's worth including in the Flatpak. I have therefore opened a PR, #15, to get this partial fix integrated into the Flatpak itself. The information I mentioned here is also in that PR, but I thought I'd repeat it here anyway.

@aplatypus @zWhdmB5T [I just had the test build for my new PR rebuilt recently](https://github.com/flathub/org.processing.processingide/pull/15#issuecomment-1744793669). After installing this new test build (`flatpak install --user https://dl.flathub.org/build-repo/53364/org.processing.processingide.flatpakref`), I'd like both of you to not only try opening Python sketches with it, but also try **stopping** the running of them with it too. Report back to me either here or in the PR as soon as you can, ideally providing error messages where possible. I'll wait until you've both done so (rebuilding the test build if or when need be), then I'll update [the appdata.xml patch file](https://github.com/flathub/org.processing.processingide/blob/master/processing-update-appdata.patch) to include this new information (so it shows up on Processing's Flathub page), and then once a final test build is built, I should be able to merge the fix and push it to Flathub. Your feedback here is highly appreciated and I look forward to hearing back from both of you :+1:

**Comment by Zishan-Rahman** [comment]
@aplatypus @zWhdmB5T Hello again, and sorry for the pings. It's been a while since I made my PR so a few days ago I decided to merge it anyway. I'd still appreciate your feedback here on whether or not your are able to run **and** close Python sketches through the IDE. Anyone else who's reading this can try this out and chime in as well.

Note that [the repository hosting Processing's Python mode](https://github.com/jdf/processing.py) is currently unmaintained, but since it became unmaintained relatively recently, and the old maintainer's currently seeking a new maintainer, it's not a _huge_ concern _just_ yet, at least in my opinion. I'm hopeful that a new maintainer can be found as soon as possible and that the transition of repository ownership will be as smooth as possible.

**Comment by Zishan-Rahman** [comment]
Looks like a maintainer for Processing's Python mode hasn't been found yet, so I added this information to the list of known issues in the AppData patch in PR #17, which has just been merged. It can still be installed and run within the Processing IDE, and therefore in this Flatpak, but I just thought the information should be out there so as not to leave anyone clueless.
